
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:

  - target:
      kind: DaemonSet
      name: node-agent

    patch: |
      - op: replace
        path: /metadata/namespace
        value: kube-system

  - target:
      kind: ClusterRoleBinding
      name: velero-core-server

    patch: |
      - op: add
        path: /subjects/1
        value:
          kind: ServiceAccount
          name: velero-core-server
          namespace: kube-system