tenant:
  name: example-tenant

pubgateway:
  name: main-gw
  namespace: core-prod
  sectionName: mylogin-https


lidarr:
  enabled: true

  image: linuxserver/lidarr
  tag: latest

  volumes:
    config:
      enabled: true

      size: 5G

    downloads:
      enabled: true

      external: true

    media:
      enabled: true

      external: true