{{- if .Values.authentik.proxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myloginspace-proxy
  labels:
    app.kubernetes.io/name: myloginspace-proxy
spec:
  replicas: {{ .Values.authentik.proxy.replicas }}

  selector:
    matchLabels:
      app.kubernetes.io/name: myloginspace-proxy

  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

  template:
    metadata:
      labels:
        app.kubernetes.io/name: myloginspace-proxy
        logs: loki-myloginspace

      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '9300'

    spec:
      restartPolicy: Always

      terminationGracePeriodSeconds: 30

      containers:
        - name: authentik-proxy
          image: ghcr.io/goauthentik/proxy:{{ include "authentik.defaultTag" $.Subcharts.authentik }}

          readinessProbe:
            failureThreshold: 3

            httpGet:
              path: /outpost.goauthentik.io/ping
              port: http-metrics
              scheme: HTTP
              httpHeaders:
                - name: Host
                  value: localhost

            initialDelaySeconds: 30
            periodSeconds: 10

            successThreshold: 1

            timeoutSeconds: 1

          securityContext:
            readOnlyRootFilesystem: true

          resources:
            requests:
              cpu: 15m
              memory: 105M

            limits:
              cpu: 500m
              memory: 512M

          ports:
            - containerPort: 9000
              name: http
              protocol: TCP

            - containerPort: 9300
              name: http-metrics
              protocol: TCP

          env:
            - name: AUTHENTIK_HOST
              value: 'http://{{ .Release.Name }}-authentik-server.{{ .Release.Namespace }}.svc.{{ .Values.cluster.domain }}'

            - name: AUTHENTIK_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: aaa-proxy-credentials

            - name: AUTHENTIK_INSECURE
              value: 'true'
{{- end }}
