apiVersion: vault.vault.upbound.io/v1alpha1
kind: MountTune
metadata:
  name: pki-int-tune
spec:
  providerConfigRef:
    name: vault-provider

  forProvider:
    path: pki_int
    maxLeaseTtlSeconds: 315360000   # 10 years