apiVersion: v1
kind: Service
metadata:
  name: psql

  labels:
    lan-mode: private
    wan-mode: public

  annotations:
    external-dns.alpha.kubernetes.io/hostname: psql-main.mylogin.space

spec:
  type: ClusterIP

  ports:
    - name: postgresql

      protocol: TCP
      appProtocol: postgresql

      port: 5432
      targetPort: psql

  selector:
    app.kubernetes.io/name: pgpool