tenant:
  name: example-tenant

pubgateway:
  name: main-gw
  namespace: core-prod
  sectionName: mylogin-https

sonarr:
  enabled: true

  image: linuxserver/sonarr

  tag: latest

  volumes:
    config:
      enabled: true

      size: 5G

    media:
      enabled: true

      external: true

    downloads:
      enabled: true

      external: true

crossplane:
  enabled: true

  jellyfin:
    enabled: true

    provider:
      name: test

prefetcharr:
  enabled: true

  image: phueber/prefetcharr

  tag: '1.3.0'