tenant:
  name: example-tenant

volumes:
  enabled: true

  downloads:
    enabled: true

    size: 80G

  media:
    enabled: true

    size: 50G

flaresolverr:
  enabled: true

  image: ghcr.io/flaresolverr/flaresolverr
  tag: latest

  volumes:
    config:
      enabled: true

      size: 5G
