tenant:
  name: example-tenant

pubgateway:
  name: main-gw
  namespace: core-prod
  sectionName: mylogin-https

radarr:
  enabled: true

  image: linuxserver/radarr

  tag: latest

  volumes:
    config:
      enabled: true

      size: 2G

    downloads:
      enabled: true

      external: true

    media:
      enabled: true

      external: true