tenant:
  name: example-tenant

pubgateway:
  name: main-gw
  namespace: core-prod
  sectionName: mylogin-https

jellyfin:
  enabled: true

  image: jellyfin/jellyfin

  tag: '10'

  volumes:
    config:
      enabled: true

    media:
      enabled: true

      external: true