hub: false


cluster:
  name: k8s
  domain: cluster.local

gateway:
  name: main-gw
  namespace: core-prod
  sectionName: https-myloginspace

datacenter: dc1

region: yxl

cachet:
  enabled: true

  creds:
    secretSync:
      enabled: true

      secretStorePath: Security/DefectDojo/Auth

      secretStoreRefs:
        - kind: ClusterSecretStore
          name: mainvault-core

  database:
    host: psql-int.mylogin.space
    port: 5432

  postgresql:
    enabled: false