pubgateway:
  name: main-gw
  namespace: core-prod
  sectionName: mylogin-https

tenant:
  name: example-tenant

sabnzbd:
  enabled: true

  image: linuxserver/sabnzbd
  tag: latest


  volumes:
    config:
      enabled: true

    downloads:
      enabled: true

prowlarr:
  enabled: true

  image: linuxserver/prowlarr
  tag: latest

  volumes:
    config:
      enabled: true