pubgateway:
  name: main-gw
  namespace: core-prod
  sectionName: mylogin-https

sabnzbd:
  enabled: true

  image: linuxserver/sabnzbd
  tag: latest


  volumes:
    config:
      enabled: true

    downloads:
      enabled: true